name: Tag and Release

on:
  workflow_call:
    inputs:
      create:
        required: true
        type: boolean
      tag:
        required: true
        type: string

jobs:
  tag-and-release:
    if: ${{ inputs.create }}
    runs-on: ubuntu-latest
    permissions:
      contents: write    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0

      - name: Create tag
        uses: rickstaa/action-create-tag@v1.7.2
        with:
          tag: ${{ inputs.tag }}

      - name: Create release
        uses: ncipollo/release-action@v1.20.0
        with:
          tag:  ${{ inputs.tag }}
